version: '3'

services: 
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g:latest
    container_name: "oracle-db"
    ports:
      - 1521:1521
      - 5500:5500
      #- 8081:8080
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - TZ=GMT
  websphere:
    build:
      dockerfile: DockerfileLiberty
      context: .
    #image: openliberty-test:latest
    container_name: "openliberty-app"
    ports:
      - 9080:9080 # http
      - 9060:9060 # console
      - 9444:9443 # https
      - 7777:7777 # debug
    #volumes:
    #- "./docker/target:/config/dropins"
    environment:
      - JAVA_OPTS=-Duser.timezone=GMT -Ddefault.client.encoding=UTF-8
      - TZ=GMT
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=7777
#      - WLP_LOGGING_MESSAGE_FORMAT=json
#      - WLP_LOGGING_CONSOLE_FORMAT=json
#      - WLP_LOGGING_CONSOLE_SOURCE=message,trace,accessLog,ffdc
#      - WLP_LOGGING_MESSAGE_SOURCE=
#      - WLP_LOGGING_CONSOLE_LOGLEVEL=info

  mq-ibm:
    #image: ibmcom/mq:latest
    build:
      dockerfile: DockerfileMQ
      context: .
    container_name: mq
    ports:
      - 1414:1414
      - 9443:9443
#    volumes:
#      - "./docker/mq/directory:/opt/mqm"
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_ADMIN_PASSWORD=passw0rd # user=admin
      - MQ_ENABLE_METRICS=true

  wildfly:
    build: docker/wildfly
    container_name: "wildfly"
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - "./deployments:/opt/jboss/wildfly/standalone/deployments"

##   ActiveMQ:61616 => "admin":"adminactivemq"
##   ActiveMQWeb:8161 => "admin":"admin"
  activemq:
    image: rmohr/activemq:5.10.0
    container_name: "activemq"
    ports:
      - "61616:61616"
      - "8161:8161"